- name: Examples of show version juniper
  hosts: HCM001ILL02
  connection: local
  gather_facts: no
  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: 830 
        timeout: 5
    - name: Print version
      debug:
        var: junos.version
